services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: open-forum-postgres
    restart: always
    environment:
      POSTGRES_DB: open_forum
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    secrets:
      - postgres_password
    networks:
      - open-forum-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d open_forum"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    security_opt:
      - no-new-privileges:true

  # NestJS Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        BUILDKIT_INLINE_CACHE: 1
      cache_from:
        - open-forum-app:latest
    image: open-forum-app:latest
    container_name: open-forum-app
    restart: always
    env_file:
      - .env.production
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - open-forum-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 512M
          cpus: '0.5'
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /app/.npm

  # Migration Service
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    image: open-forum-app:latest
    profiles:
      - migrate
    command: npx typeorm migration:run -d dist/core/database/data-source.js
    env_file:
      - .env.production
    networks:
      - open-forum-network
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: open-forum-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/certbot/conf:/etc/letsencrypt:ro
      - ./data/certbot/www:/var/www/certbot:ro
      - ./nginx/logs:/var/log/nginx
      - ./uploads:/var/www/uploads:ro
    networks:
      - open-forum-network
    depends_on:
      app:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'
    security_opt:
      - no-new-privileges:true

volumes:
  postgres_data:

networks:
  open-forum-network:
    driver: bridge

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt