import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1751529646113 implements MigrationInterface {
    name = 'InitialMigration1751529646113'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'lecturer', 'student')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "username" character varying(100) NOT NULL, "password" character varying(100), "full_name" character varying(100) NOT NULL, "gender" character varying(1), "batch_year" character varying(4), "education_level" character varying(10), "study_program_id" integer, "email" character varying(100), "phone" character varying(20), "avatar_url" character varying(255), "role" "public"."users_role_enum" NOT NULL DEFAULT 'student', "last_active_at" TIMESTAMP, "is_external" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fe0bb3f6520ee0469504521e71" ON "users" ("username") `);
        await queryRunner.query(`CREATE TABLE "study_programs" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "study_program_code" character varying(20) NOT NULL, "education_level" character varying(50), "study_program_name" character varying(200) NOT NULL, "faculty_id" integer NOT NULL, "director_name" character varying(200), CONSTRAINT "PK_50d4f2af3aaed906866eac7e651" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_34fd0ce3e2800fd813ae049a69" ON "study_programs" ("study_program_code") `);
        await queryRunner.query(`CREATE TYPE "public"."attachments_entity_type_enum" AS ENUM('discussion', 'comment')`);
        await queryRunner.query(`CREATE TABLE "attachments" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "original_name" character varying(255) NOT NULL, "name" character varying(255) NOT NULL, "mime_type" character varying(100) NOT NULL, "size" integer NOT NULL, "url" character varying(500) NOT NULL, "entity_type" "public"."attachments_entity_type_enum" NOT NULL, "entity_id" integer NOT NULL, "is_image" boolean NOT NULL DEFAULT false, "display_order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_5e1f050bcff31e3084a1d662412" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a893a08d151195e1d3bf7a109c" ON "attachments" ("entity_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_f627d55b75ca1d0c0012a4a93a" ON "attachments" ("entity_id") `);
        await queryRunner.query(`CREATE TABLE "comment_mentions" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "comment_id" integer NOT NULL, "user_id" integer NOT NULL, CONSTRAINT "PK_96cd7c00d35e056fcebb7725e02" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "comments" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "content" text NOT NULL, "author_id" integer NOT NULL, "is_edited" boolean NOT NULL DEFAULT false, "discussion_id" integer NOT NULL, "parent_id" integer, "upvote_count" integer NOT NULL DEFAULT '0', "downvote_count" integer NOT NULL DEFAULT '0', "reply_count" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d6f93329801a93536da4241e38" ON "comments" ("parent_id") `);
        await queryRunner.query(`CREATE TABLE "discussions" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "content" text NOT NULL, "is_anonymous" boolean NOT NULL DEFAULT false, "author_id" integer NOT NULL, "comment_count" integer NOT NULL DEFAULT '0', "upvote_count" integer NOT NULL DEFAULT '0', "downvote_count" integer NOT NULL DEFAULT '0', "tags" text array DEFAULT '{}', "space_id" integer, "is_edited" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_4b3d110d8e5d9077ddc0a0d1b4c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."discussion_spaces_space_type_enum" AS ENUM('academic', 'faculty', 'study_program', 'organization', 'campus', 'other')`);
        await queryRunner.query(`CREATE TABLE "discussion_spaces" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "name" character varying(100) NOT NULL, "description" text, "slug" character varying(100) NOT NULL, "creator_id" integer NOT NULL, "space_type" "public"."discussion_spaces_space_type_enum" NOT NULL DEFAULT 'other', "faculty_id" integer, "study_program_id" integer, "icon_url" character varying(255), "banner_url" character varying(255), "follower_count" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_fd8dd64173fad798693ca2df762" UNIQUE ("slug"), CONSTRAINT "PK_5723b93e8d863c05d926cebb557" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fd8dd64173fad798693ca2df76" ON "discussion_spaces" ("slug") `);
        await queryRunner.query(`CREATE TABLE "faculties" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "faculty_code" character varying(20) NOT NULL, "faculty_name" character varying(200) NOT NULL, "faculty_abbreviation" character varying(20) NOT NULL, "dean_name" character varying(200), "vice_dean_1_name" character varying(200), "vice_dean_2_name" character varying(200), "vice_dean_3_name" character varying(200), CONSTRAINT "UQ_687621e932733f71e30a0a1faec" UNIQUE ("faculty_code"), CONSTRAINT "PK_fd83e4a09c7182ccf7bdb3770b9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_687621e932733f71e30a0a1fae" ON "faculties" ("faculty_code") `);
        await queryRunner.query(`CREATE TYPE "public"."user_activities_type_enum" AS ENUM('create_discussion', 'create_comment', 'vote_discussion', 'vote_comment', 'bookmark_discussion', 'remove_bookmark', 'follow_space', 'unfollow_space', 'report_content', 'edit_discussion', 'edit_comment', 'delete_discussion', 'delete_comment')`);
        await queryRunner.query(`CREATE TYPE "public"."user_activities_entity_type_enum" AS ENUM('discussion', 'comment', 'discussion_space', 'report', 'user')`);
        await queryRunner.query(`CREATE TABLE "user_activities" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" integer NOT NULL, "type" "public"."user_activities_type_enum" NOT NULL, "entity_type" "public"."user_activities_entity_type_enum" NOT NULL, "entity_id" integer NOT NULL, "metadata" jsonb NOT NULL DEFAULT '{}', "ip_address" character varying(45), "user_agent" character varying(255), CONSTRAINT "PK_1245d4d2cf04ba7743f2924d951" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_198770cc5d9ee9e9260888302b" ON "user_activities" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd789c573f3fd7da3b22f724fd" ON "user_activities" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "bookmarks" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" integer NOT NULL, "discussion_id" integer NOT NULL, CONSTRAINT "UQ_9060ca43dad4787504cdc356a1b" UNIQUE ("user_id", "discussion_id"), CONSTRAINT "PK_7f976ef6cecd37a53bd11685f32" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('new_comment', 'new_discussion', 'new_reply', 'discussion_upvote', 'comment_upvote', 'report_reviewed', 'user_mentioned')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_entity_type_enum" AS ENUM('discussion', 'comment', 'report', 'discussion_space', 'user')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "recipient_id" integer NOT NULL, "actor_id" integer, "type" "public"."notifications_type_enum" NOT NULL, "entity_type" "public"."notifications_entity_type_enum" NOT NULL, "entity_id" integer NOT NULL, "data" jsonb NOT NULL DEFAULT '{}', "is_read" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5332a4daa46fd3f4e6625dd275" ON "notifications" ("recipient_id") `);
        await queryRunner.query(`CREATE TYPE "public"."reports_target_type_enum" AS ENUM('discussion', 'comment')`);
        await queryRunner.query(`CREATE TYPE "public"."reports_status_enum" AS ENUM('pending', 'resolved', 'dismissed')`);
        await queryRunner.query(`CREATE TABLE "reports" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "reporter_id" integer NOT NULL, "target_type" "public"."reports_target_type_enum" NOT NULL, "target_id" integer NOT NULL, "reason_id" integer NOT NULL, "description" text, "status" "public"."reports_status_enum" NOT NULL DEFAULT 'pending', "reviewer_id" integer, "reviewed_at" TIMESTAMP, CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9f4244cd79aecec15dd41a2c73" ON "reports" ("target_type", "target_id") `);
        await queryRunner.query(`CREATE TABLE "report_reasons" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "name" character varying(100) NOT NULL, "description" text, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_b3e556babb07559ce99a7fb158e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."votes_entity_type_enum" AS ENUM('discussion', 'comment')`);
        await queryRunner.query(`CREATE TABLE "votes" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "entity_type" "public"."votes_entity_type_enum" NOT NULL, "entity_id" integer NOT NULL, "value" integer NOT NULL, "user_id" integer NOT NULL, CONSTRAINT "PK_f3d9fd4a0af865152c3f59db8ff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "push_subscriptions" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "userId" integer NOT NULL, "endpoint" character varying NOT NULL, "p256dh" character varying NOT NULL, "auth" character varying NOT NULL, "active" boolean NOT NULL DEFAULT true, "userAgent" character varying, CONSTRAINT "UQ_0008bdfd174e533a3f98bf9af16" UNIQUE ("endpoint"), CONSTRAINT "PK_757fc8f00c34f66832668dc2e53" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4cc061875e9eecc311a94b3e43" ON "push_subscriptions" ("userId") `);
        await queryRunner.query(`CREATE TABLE "discussion_space_followers" ("space_id" integer NOT NULL, "user_id" integer NOT NULL, CONSTRAINT "PK_36df393061267ceb8aedbb0ebc4" PRIMARY KEY ("space_id", "user_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_90ad6c411b7a54e12110f6d673" ON "discussion_space_followers" ("space_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f4f78f05248b172b42025e06c0" ON "discussion_space_followers" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_fa164833ac33819e7976d01b50f" FOREIGN KEY ("study_program_id") REFERENCES "study_programs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "study_programs" ADD CONSTRAINT "FK_317def4b66d5e83811b9e65832a" FOREIGN KEY ("faculty_id") REFERENCES "faculties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_mentions" ADD CONSTRAINT "FK_9ac3fac766fa09176e5c53e4d3f" FOREIGN KEY ("comment_id") REFERENCES "comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_mentions" ADD CONSTRAINT "FK_a29d739a2d28fb38b8b591f8152" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_e6d38899c31997c45d128a8973b" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_a7449e08115d74692551b12ff1d" FOREIGN KEY ("discussion_id") REFERENCES "discussions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_d6f93329801a93536da4241e386" FOREIGN KEY ("parent_id") REFERENCES "comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discussions" ADD CONSTRAINT "FK_cedb0b583906c7f01fc7bd4972c" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discussions" ADD CONSTRAINT "FK_c49c16cd1783ddb8f4e5d2f9b15" FOREIGN KEY ("space_id") REFERENCES "discussion_spaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discussion_spaces" ADD CONSTRAINT "FK_35960d2096a28ea7496d4bb4409" FOREIGN KEY ("faculty_id") REFERENCES "faculties"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discussion_spaces" ADD CONSTRAINT "FK_ec8d5e172c5e2b5344427f29a6b" FOREIGN KEY ("study_program_id") REFERENCES "study_programs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_activities" ADD CONSTRAINT "FK_a283f37e08edf5e37d38b375eec" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookmarks" ADD CONSTRAINT "FK_58a0fbaee65cd8959a870ee678c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookmarks" ADD CONSTRAINT "FK_a5bde76ee72b9dc9a98b538eef1" FOREIGN KEY ("discussion_id") REFERENCES "discussions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_5332a4daa46fd3f4e6625dd275d" FOREIGN KEY ("recipient_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_20f8b51fd9655c0b69feed5efc6" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_9459b9bf907a3807ef7143d2ead" FOREIGN KEY ("reporter_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_4371b0fe6ae95fb5663bc25c634" FOREIGN KEY ("reason_id") REFERENCES "report_reasons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_8a771ab9cef7da26ac94fb11d92" FOREIGN KEY ("reviewer_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "votes" ADD CONSTRAINT "FK_27be2cab62274f6876ad6a31641" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" ADD CONSTRAINT "FK_4cc061875e9eecc311a94b3e431" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discussion_space_followers" ADD CONSTRAINT "FK_90ad6c411b7a54e12110f6d673f" FOREIGN KEY ("space_id") REFERENCES "discussion_spaces"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "discussion_space_followers" ADD CONSTRAINT "FK_f4f78f05248b172b42025e06c08" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "discussion_space_followers" DROP CONSTRAINT "FK_f4f78f05248b172b42025e06c08"`);
        await queryRunner.query(`ALTER TABLE "discussion_space_followers" DROP CONSTRAINT "FK_90ad6c411b7a54e12110f6d673f"`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" DROP CONSTRAINT "FK_4cc061875e9eecc311a94b3e431"`);
        await queryRunner.query(`ALTER TABLE "votes" DROP CONSTRAINT "FK_27be2cab62274f6876ad6a31641"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_8a771ab9cef7da26ac94fb11d92"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_4371b0fe6ae95fb5663bc25c634"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_9459b9bf907a3807ef7143d2ead"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_20f8b51fd9655c0b69feed5efc6"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_5332a4daa46fd3f4e6625dd275d"`);
        await queryRunner.query(`ALTER TABLE "bookmarks" DROP CONSTRAINT "FK_a5bde76ee72b9dc9a98b538eef1"`);
        await queryRunner.query(`ALTER TABLE "bookmarks" DROP CONSTRAINT "FK_58a0fbaee65cd8959a870ee678c"`);
        await queryRunner.query(`ALTER TABLE "user_activities" DROP CONSTRAINT "FK_a283f37e08edf5e37d38b375eec"`);
        await queryRunner.query(`ALTER TABLE "discussion_spaces" DROP CONSTRAINT "FK_ec8d5e172c5e2b5344427f29a6b"`);
        await queryRunner.query(`ALTER TABLE "discussion_spaces" DROP CONSTRAINT "FK_35960d2096a28ea7496d4bb4409"`);
        await queryRunner.query(`ALTER TABLE "discussions" DROP CONSTRAINT "FK_c49c16cd1783ddb8f4e5d2f9b15"`);
        await queryRunner.query(`ALTER TABLE "discussions" DROP CONSTRAINT "FK_cedb0b583906c7f01fc7bd4972c"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_d6f93329801a93536da4241e386"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_a7449e08115d74692551b12ff1d"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_e6d38899c31997c45d128a8973b"`);
        await queryRunner.query(`ALTER TABLE "comment_mentions" DROP CONSTRAINT "FK_a29d739a2d28fb38b8b591f8152"`);
        await queryRunner.query(`ALTER TABLE "comment_mentions" DROP CONSTRAINT "FK_9ac3fac766fa09176e5c53e4d3f"`);
        await queryRunner.query(`ALTER TABLE "study_programs" DROP CONSTRAINT "FK_317def4b66d5e83811b9e65832a"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_fa164833ac33819e7976d01b50f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4f78f05248b172b42025e06c0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_90ad6c411b7a54e12110f6d673"`);
        await queryRunner.query(`DROP TABLE "discussion_space_followers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4cc061875e9eecc311a94b3e43"`);
        await queryRunner.query(`DROP TABLE "push_subscriptions"`);
        await queryRunner.query(`DROP TABLE "votes"`);
        await queryRunner.query(`DROP TYPE "public"."votes_entity_type_enum"`);
        await queryRunner.query(`DROP TABLE "report_reasons"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f4244cd79aecec15dd41a2c73"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP TYPE "public"."reports_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reports_target_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5332a4daa46fd3f4e6625dd275"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_entity_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TABLE "bookmarks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd789c573f3fd7da3b22f724fd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_198770cc5d9ee9e9260888302b"`);
        await queryRunner.query(`DROP TABLE "user_activities"`);
        await queryRunner.query(`DROP TYPE "public"."user_activities_entity_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_activities_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_687621e932733f71e30a0a1fae"`);
        await queryRunner.query(`DROP TABLE "faculties"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fd8dd64173fad798693ca2df76"`);
        await queryRunner.query(`DROP TABLE "discussion_spaces"`);
        await queryRunner.query(`DROP TYPE "public"."discussion_spaces_space_type_enum"`);
        await queryRunner.query(`DROP TABLE "discussions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d6f93329801a93536da4241e38"`);
        await queryRunner.query(`DROP TABLE "comments"`);
        await queryRunner.query(`DROP TABLE "comment_mentions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f627d55b75ca1d0c0012a4a93a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a893a08d151195e1d3bf7a109c"`);
        await queryRunner.query(`DROP TABLE "attachments"`);
        await queryRunner.query(`DROP TYPE "public"."attachments_entity_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_34fd0ce3e2800fd813ae049a69"`);
        await queryRunner.query(`DROP TABLE "study_programs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe0bb3f6520ee0469504521e71"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
    }

}
