---
# Discussion Creation Load Test Configuration
#----------------------------------------------------------------------
config:
  target: 'http://localhost:3000/api/v1'

  phases:
    - name: 'Warmup Phase'
      duration: 60
      arrivalRate: 1
      rampTo: 8
      comment: 'Gradually increase load to warm up the system'

    # - name: 'Sustained Load Phase'
    #   duration: 180
    #   arrivalRate: 8
    #   comment: 'Maintain steady load to evaluate stability'

    # - name: 'Peak Load Phase'
    #   duration: 120
    #   arrivalRate: 8
    #   rampTo: 25
    #   comment: 'Ramp up to peak load to identify breaking points'

  processor: '../scripts/helpers.js'

  plugins:
    expect: {}

  thresholds:
    http.response_time.median: 400
    http.response_time.p95: 1000
    http.response_time.p99: 2000
    http.errors: 1
    http.request_rate: 5
    'socketio.latency.median': 200
    'socketio.latency.p95': 500

  http:
    timeout: 15000

#----------------------------------------------------------------------
# Test Scenarios
#----------------------------------------------------------------------
scenarios:
  - name: 'Create discussions with text only'
    weight: 80
    flow:
      - loop:
          # Generate random discussion data
          - function: 'generateDiscussionData'

          # Capture timestamp for e2e latency
          - function: 'captureTimestamp'

          # Create discussion via API
          - post:
              url: '/discussions'
              beforeRequest: 'setAuthHeader'
              json:
                content: '{{ content }}'
                isAnonymous: '{{ isAnonymous }}'
                tags: '{{ tags }}'
                spaceId: '{{ spaceId }}'
                clientRequestTime: '{{ timestamp }}'
              capture:
                - json: '$.data.id'
                  as: 'discussionId'
              expect:
                - statusCode: 201
        count: 3

  - name: 'Create discussions with file attachments'
    weight: 20
    flow:
      - loop:
          # Generate random discussion data
          - function: 'generateDiscussionData'

          # Generate random file attachments
          - function: 'generateFileAttachments'

          # Create discussion with attachments via custom function
          - function: 'createDiscussionWithAttachments'

          # Optional: Add a think time to simulate user attaching files
          - think: 2
        count: 2
