---
#----------------------------------------------------------------------
# Discussion Creation Load Test Configuration
#----------------------------------------------------------------------
config:
  # API endpoint configuration
  target: 'http://localhost:3000/api/v1'

  # Test execution phases
  phases:
    - name: 'Warmup Phase'
      duration: 60
      arrivalRate: 1
      rampTo: 8
      comment: 'Gradually increase load to warm up the system'

    # - name: 'Sustained Load Phase'
    #   duration: 180
    #   arrivalRate: 8
    #   comment: 'Maintain steady load to evaluate stability'

    # - name: 'Peak Load Phase'
    #   duration: 120
    #   arrivalRate: 8
    #   rampTo: 25
    #   comment: 'Ramp up to peak load to identify breaking points'

  # Helper scripts
  processor: '../scripts/load-test-helpers.js'

  # Plugins configuration
  plugins:
    metrics-by-endpoint: {} # Track metrics per endpoint
    expect: {} # Response validation

  # Performance thresholds
  thresholds:
    http.response_time.median: 400 # 50% of requests should be under 400ms
    http.response_time.p95: 1000 # 95% of requests should be under 1000ms
    http.response_time.p99: 2000 # 99% of requests should be under 2000ms
    http.errors: 1 # Error rate threshold (percentage)
    http.request_rate: 5 # Minimum request rate
    'socketio.latency.median': 200
    'socketio.latency.p95': 500

#----------------------------------------------------------------------
# Test Scenarios
#----------------------------------------------------------------------
scenarios:
  - name: 'Create discussions with text only'
    weight: 80 # 80% of virtual users run this scenario
    flow:
      - loop:
          # Generate random discussion data
          - function: 'generateDiscussionData'

          # Create discussion via API
          - post:
              url: '/discussions'
              beforeRequest: 'setAuthHeader'
              json:
                content: '{{ content }}'
                isAnonymous: '{{ isAnonymous }}'
                tags: '{{ tags }}'
                spaceId: '{{ spaceId }}'
              capture:
                - json: '$.data.id'
                  as: 'discussionId'
              expect:
                - statusCode: 201
        count: 3

  - name: 'Create discussions with file attachments'
    weight: 20 # 20% of virtual users run this scenario
    flow:
      - loop:
          # Generate random discussion data
          - function: 'generateDiscussionData'

          # Generate random file attachments
          - function: 'generateFileAttachments'

          # Create discussion with attachments via custom function
          - function: 'createDiscussionWithAttachments'

          # Optional: Add a think time to simulate user attaching files
          - think: 2
        count: 2
