#----------------------------------------------------------------------
# Comment Notification Performance Test - Author-Specific
#----------------------------------------------------------------------
config:
  target: 'http://localhost:3000/api/v1'

  phases:
    - name: 'Warmup Phase'
      duration: 60
      arrivalRate: 1
      rampTo: 8
      comment: 'Gradually increase load to warm up the system'

    # - name: 'Sustained Load Phase'
    #   duration: 180
    #   arrivalRate: 8
    #   comment: 'Maintain steady load to evaluate stability'

    # - name: 'Peak Load Phase'
    #   duration: 120
    #   arrivalRate: 8
    #   rampTo: 25
    #   comment: 'Ramp up to peak load to identify breaking points'

  processor: '../scripts/helpers.js'

  plugins:
    expect: {}

  variables:
    targetAuthorId: 39

  thresholds:
    http.response_time.median: 300
    http.response_time.p95: 800
    http.response_time.p99: 1500
    http.errors: 1
    http.request_rate: 5

  http:
    timeout: 15000

before:
  flow:
    - function: 'preFetchDiscussionsByAuthor'
    - think: 1

scenarios:
  - name: 'Vote on author-specific discussions'
    flow:
      # Load pre-fetched discussion IDs
      - function: 'loadDiscussionIds'
      - function: 'checkDiscussionId'

      - loop:
          # Capture timestamp for e2e latency
          - function: 'captureTimestamp'

          # Post vote to the discussion
          - post:
              url: '/discussions/{{ discussionId }}/votes'
              beforeRequest: 'setAuthHeader'
              json:
                value: 1
                clientRequestTime: '{{ timestamp }}'
              expect:
                - statusCode: 200

          # Small delay to ensure WebSocket notification completes
          - think: 1
        count: 5
